### ISSUE TITLE
openidm community edition binary doesn't start

### ISSUE THREAD

**Issue by rdoetjes** [ForgeRock/openidm-community-edition#7]
After unzipping and launching the startup.sh (or startup.bat) you are confronted with the message:
Error: Could not find or load main class org.forgerock.commons.launcher.Main
Classpath's I have checked and the point to /opt/openidm/bin/* and /opt/openidm/framework/*

I do have to say that I am running a Java 8 jre (whilst I see that the build requires a rather outdated 1.6 -- my question to that is why is that? I think it's been out of public updates since 2013)

**Comment by BohoCode** [comment]
I've got somewhere with this. Not all the jars were getting packed correctly. Will update soon, but there are further deeper issues to investigate. More updates soon. Thanks for reporting.

**Comment by m4ci3k2** [comment]
I get the same error when I build from source (using openjdk6 on Debian 7), so just building your own won't help.

**Comment by posledov** [comment]
Hello, guys.
I've got the same problem (Centos 7, OpenJDK 1.8.0.131)

**Comment by cgdrake** [comment]
OpenIDM is failing to start as a result of a problem with the [forgerock-launcher](http://maven.forgerock.org/repo/webapp/#/artifacts/browse/tree/General/community/org/forgerock/ce/commons/launcher-zip/1.0.0) dependency.  The forgerock-launcher v1.0.0 artifact on maven.forgerock.org is missing the bin/launcher.jar file, as a result it is not packaged in the OpenIDM zip and causes the product to fail at startup.

**Comment by sayntabey** [comment]
Hello guys,
I have the same problem (Ubuntu Server 16.04, java version "1.8.0_131", openidm-2.1.2.zip from the github binary release page). This is the exact error it throws "Error: Could not find or load main class org.forgerock.commons.launcher.Main"

**Comment by rdoetjes** [comment]
Can I conclude that OpenIDM CE is dead? To me it seems that the maintainers withdrew

**Comment by rafbueno** [comment]
@cgdrake and @BohoCode I saw the fix code, but the error still happens.

**Try:**

```
git clone https://github.com/BohoCode/openidm-community-edition-2.1.2.git
git checkout bugfix/#7-binary-wont-start
cd openidm-zip
mvn clean install
cp target/openidm-2.1.2.zip /opt
cd /opt
unzip openidm-2.1.2.zip
```

or 

```
git clone https://github.com/cgdrake/openidm-community-edition.git
git checkout bugfix/issue#7 
cd openidm-zip
mvn clean install
cp target/openidm-2.1.2.zip /opt
cd /opt
unzip openidm-2.1.2.zip
```

**Result:** 

```
root@d13dad2004b7:/opt/openidm# ./startup.sh
Executing ./startup.sh...
Using OPENIDM_HOME:   /opt/openidm
Using OPENIDM_OPTS:   -Xmx1024m
Using LOGGING_CONFIG: -Djava.util.logging.config.file=/opt/openidm/conf/logging.
properties
Error: Could not find or load main class org.forgerock.commons.launcher.Mai
```

**Comment by cgdrake** [comment]
@rafbueno The PR I submitted only addressed some of the issues, there are two remaining issues that I can see:

1. The `bin/launcher.jar` file is missing from the OpenIDM zip file and is a result of a problem with the ForgeRock Maven repository rather than an issue with the OpenIDM CE project itself.
2. The `connector-framework-internal-1.1.1.0.jar` file specifies an incorrect OSGi Fragment-Host within the manifest. See [PR #2](https://github.com/ForgeRock/openicf-java-framework-community-edition/pull/2).

In order to build and then run the OpenIDM Community Edition you will need to:
1. Clone the `commons-forgerock-launcher-community-edition` repository and build it locally
2. Checkout commit [28f6ce86c5c2aeb9e4b7fb18826341418c91d43a](https://github.com/ForgeRock/openicf-java-framework-community-edition/tree/28f6ce86c5c2aeb9e4b7fb18826341418c91d43a) from the `openicf-java-framework-community-edition` project and build it locally
3. Checkout commit [3872e30525a48ca60a00d928f0d2090d71b15df8](https://github.com/ForgeRock/openidm-community-edition/commit/3872e30525a48ca60a00d928f0d2090d71b15df8) from the `openidm-community-edition` repository and build it locally
4. Unzip the `openidm-2.1.2.zip` file and copy the `launcher/target/launcher-1.0.0.jar` file from the `openicf-java-framework-community-edition` project to the OpenIDM `bin` folder.

Hopefully the above will get things working for you.

**Comment by cgdrake** [comment]
New artifacts have been pushed to the ForgeRock maven repository for the various OpenIDM CE dependencies which were preventing a clean build and startup of the server.

When building OpenIDM CE 2.1.2, be sure to force update the dependencies with the Maven -U option.
